[2025-10-09T03:10:31.691+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.702+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.703+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.704+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.705+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.719+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-08 00:00:00+00:00
[2025-10-09T03:10:31.725+0000] {standard_task_runner.py:55} INFO - Started process 3153 to run task
[2025-10-09T03:10:31.728+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-08T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpz_9fc1ne']
[2025-10-09T03:10:31.730+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask load_customer
[2025-10-09T03:10:31.853+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.926+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-08T00:00:00+00:00
[2025-10-09T03:10:31.930+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.930+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.942+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251008T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.981+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.995+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.653+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.663+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.663+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.664+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.664+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.678+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-08 00:00:00+00:00
[2025-10-09T04:08:08.683+0000] {standard_task_runner.py:55} INFO - Started process 4179 to run task
[2025-10-09T04:08:08.686+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmp_u0p8x_6']
[2025-10-09T04:08:08.688+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask load_customer
[2025-10-09T04:08:08.779+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.855+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-08T00:00:00+00:00
[2025-10-09T04:08:08.858+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.859+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.869+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251008T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.899+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.921+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.959+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.972+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.972+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.973+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.974+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.992+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-08 00:00:00+00:00
[2025-10-09T04:16:15.997+0000] {standard_task_runner.py:55} INFO - Started process 610 to run task
[2025-10-09T04:16:16.001+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpz007lxm1']
[2025-10-09T04:16:16.003+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask load_customer
[2025-10-09T04:16:16.102+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:16.169+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-08T00:00:00+00:00
[2025-10-09T04:16:16.191+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:16.192+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:16.204+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251008T000000, start_date=20251009T041615, end_date=20251009T041616
[2025-10-09T04:16:16.254+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:16.273+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:27.368+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.381+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.382+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.382+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:27.383+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.398+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-08 00:00:00+00:00
[2025-10-09T04:41:27.406+0000] {standard_task_runner.py:55} INFO - Started process 1333 to run task
[2025-10-09T04:41:27.409+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-08T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpuw9_nt2u']
[2025-10-09T04:41:27.411+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask load_customer
[2025-10-09T04:41:27.508+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-08T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.577+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-08T00:00:00+00:00
[2025-10-09T04:41:27.610+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.611+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.620+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251008T000000, start_date=20251009T044127, end_date=20251009T044127
[2025-10-09T04:41:27.663+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.689+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
