[2025-10-09T03:10:31.230+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.244+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.245+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.246+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.247+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.271+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-03 00:00:00+00:00
[2025-10-09T03:10:31.279+0000] {standard_task_runner.py:55} INFO - Started process 3145 to run task
[2025-10-09T03:10:31.284+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-03T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpmysp8hxz']
[2025-10-09T03:10:31.287+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask load_customer
[2025-10-09T03:10:31.410+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.499+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-03T00:00:00+00:00
[2025-10-09T03:10:31.501+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.502+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.516+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251003T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.576+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.597+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.217+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.230+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.230+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.231+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.231+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.246+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-03 00:00:00+00:00
[2025-10-09T04:08:08.253+0000] {standard_task_runner.py:55} INFO - Started process 4174 to run task
[2025-10-09T04:08:08.257+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-03T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpqegl_m6s']
[2025-10-09T04:08:08.260+0000] {standard_task_runner.py:83} INFO - Job 2: Subtask load_customer
[2025-10-09T04:08:08.379+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.466+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-03T00:00:00+00:00
[2025-10-09T04:08:08.469+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.470+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.481+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251003T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.510+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.527+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.512+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.523+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.524+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.525+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.526+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.544+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-03 00:00:00+00:00
[2025-10-09T04:16:15.550+0000] {standard_task_runner.py:55} INFO - Started process 605 to run task
[2025-10-09T04:16:15.554+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-03T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmp6qdx0eif']
[2025-10-09T04:16:15.557+0000] {standard_task_runner.py:83} INFO - Job 2: Subtask load_customer
[2025-10-09T04:16:15.681+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:15.782+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-03T00:00:00+00:00
[2025-10-09T04:16:15.814+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:15.815+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:15.833+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251003T000000, start_date=20251009T041615, end_date=20251009T041615
[2025-10-09T04:16:15.887+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:15.907+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:26.835+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:41:26.849+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [queued]>
[2025-10-09T04:41:26.850+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:26.851+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:26.851+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:26.873+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-03 00:00:00+00:00
[2025-10-09T04:41:26.880+0000] {standard_task_runner.py:55} INFO - Started process 1321 to run task
[2025-10-09T04:41:26.884+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-03T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpxaf7qjjq']
[2025-10-09T04:41:26.887+0000] {standard_task_runner.py:83} INFO - Job 2: Subtask load_customer
[2025-10-09T04:41:27.023+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-03T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.111+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-03T00:00:00+00:00
[2025-10-09T04:41:27.159+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.160+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.171+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251003T000000, start_date=20251009T044126, end_date=20251009T044127
[2025-10-09T04:41:27.219+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.242+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
