[2025-10-09T03:10:31.561+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.572+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.573+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.573+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.574+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.591+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-07 00:00:00+00:00
[2025-10-09T03:10:31.596+0000] {standard_task_runner.py:55} INFO - Started process 3150 to run task
[2025-10-09T03:10:31.600+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-07T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmp0a0723w0']
[2025-10-09T03:10:31.602+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask load_customer
[2025-10-09T03:10:31.699+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.766+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-07T00:00:00+00:00
[2025-10-09T03:10:31.769+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.769+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.780+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251007T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.813+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.832+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.552+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.564+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.565+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.565+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.566+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.580+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-07 00:00:00+00:00
[2025-10-09T04:08:08.586+0000] {standard_task_runner.py:55} INFO - Started process 4178 to run task
[2025-10-09T04:08:08.589+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-07T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmphl7bxv6a']
[2025-10-09T04:08:08.591+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask load_customer
[2025-10-09T04:08:08.685+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.752+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-07T00:00:00+00:00
[2025-10-09T04:08:08.755+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.755+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.764+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251007T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.802+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.821+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.871+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.883+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.884+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.884+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.885+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.902+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-07 00:00:00+00:00
[2025-10-09T04:16:15.909+0000] {standard_task_runner.py:55} INFO - Started process 609 to run task
[2025-10-09T04:16:15.912+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-07T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpiwfq6pzp']
[2025-10-09T04:16:15.915+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask load_customer
[2025-10-09T04:16:16.028+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:16.099+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-07T00:00:00+00:00
[2025-10-09T04:16:16.120+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:16.120+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:16.130+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251007T000000, start_date=20251009T041615, end_date=20251009T041616
[2025-10-09T04:16:16.166+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:16.182+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:27.215+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.228+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.229+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.231+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:27.232+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.252+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-07 00:00:00+00:00
[2025-10-09T04:41:27.259+0000] {standard_task_runner.py:55} INFO - Started process 1325 to run task
[2025-10-09T04:41:27.262+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-07T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmp6rl0ab2j']
[2025-10-09T04:41:27.264+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask load_customer
[2025-10-09T04:41:27.375+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-07T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.450+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-07T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-07T00:00:00+00:00
[2025-10-09T04:41:27.486+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.487+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.496+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251007T000000, start_date=20251009T044127, end_date=20251009T044127
[2025-10-09T04:41:27.516+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.531+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
