[2025-10-09T03:10:31.449+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.462+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.463+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.463+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.464+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.481+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-06 00:00:00+00:00
[2025-10-09T03:10:31.488+0000] {standard_task_runner.py:55} INFO - Started process 3149 to run task
[2025-10-09T03:10:31.492+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-06T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpo6fzgyv0']
[2025-10-09T03:10:31.498+0000] {standard_task_runner.py:83} INFO - Job 17: Subtask load_customer
[2025-10-09T03:10:31.602+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.675+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-06T00:00:00+00:00
[2025-10-09T03:10:31.677+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.677+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.689+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251006T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.744+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.759+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.419+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.430+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.432+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.432+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.433+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.450+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-06 00:00:00+00:00
[2025-10-09T04:08:08.456+0000] {standard_task_runner.py:55} INFO - Started process 4177 to run task
[2025-10-09T04:08:08.459+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpmgih9zox']
[2025-10-09T04:08:08.462+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask load_customer
[2025-10-09T04:08:08.569+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.642+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-06T00:00:00+00:00
[2025-10-09T04:08:08.645+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.646+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.656+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251006T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.672+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.692+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.745+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.760+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.761+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.762+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.763+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.781+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-06 00:00:00+00:00
[2025-10-09T04:16:15.786+0000] {standard_task_runner.py:55} INFO - Started process 608 to run task
[2025-10-09T04:16:15.791+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpktny1dbx']
[2025-10-09T04:16:15.793+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask load_customer
[2025-10-09T04:16:15.908+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:15.990+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-06T00:00:00+00:00
[2025-10-09T04:16:16.015+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:16.016+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:16.026+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251006T000000, start_date=20251009T041615, end_date=20251009T041616
[2025-10-09T04:16:16.044+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:16.063+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:27.143+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.155+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.156+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.157+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:27.158+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.175+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-06 00:00:00+00:00
[2025-10-09T04:41:27.181+0000] {standard_task_runner.py:55} INFO - Started process 1324 to run task
[2025-10-09T04:41:27.185+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-06T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpg0ry2al6']
[2025-10-09T04:41:27.189+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask load_customer
[2025-10-09T04:41:27.299+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-06T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.379+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-06T00:00:00+00:00
[2025-10-09T04:41:27.416+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.417+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.430+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251006T000000, start_date=20251009T044127, end_date=20251009T044127
[2025-10-09T04:41:27.479+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.495+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
