[2025-10-09T03:10:31.374+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.387+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.387+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.388+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.389+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.407+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-05 00:00:00+00:00
[2025-10-09T03:10:31.413+0000] {standard_task_runner.py:55} INFO - Started process 3148 to run task
[2025-10-09T03:10:31.418+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmp96phy8hk']
[2025-10-09T03:10:31.421+0000] {standard_task_runner.py:83} INFO - Job 16: Subtask load_customer
[2025-10-09T03:10:31.537+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.611+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-05T00:00:00+00:00
[2025-10-09T03:10:31.613+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.616+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.629+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251005T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.674+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.690+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.369+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.381+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.382+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.382+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.383+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.401+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-05 00:00:00+00:00
[2025-10-09T04:08:08.408+0000] {standard_task_runner.py:55} INFO - Started process 4176 to run task
[2025-10-09T04:08:08.414+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpibjprdz9']
[2025-10-09T04:08:08.417+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask load_customer
[2025-10-09T04:08:08.527+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.607+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-05T00:00:00+00:00
[2025-10-09T04:08:08.609+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.610+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.620+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251005T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.668+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.685+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.642+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.656+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.657+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.658+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.659+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.675+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-05 00:00:00+00:00
[2025-10-09T04:16:15.682+0000] {standard_task_runner.py:55} INFO - Started process 607 to run task
[2025-10-09T04:16:15.686+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpmbhbf6ba']
[2025-10-09T04:16:15.690+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask load_customer
[2025-10-09T04:16:15.814+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:15.901+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-05T00:00:00+00:00
[2025-10-09T04:16:15.927+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:15.929+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:15.944+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251005T000000, start_date=20251009T041615, end_date=20251009T041615
[2025-10-09T04:16:15.980+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:15.998+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:27.043+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.057+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [queued]>
[2025-10-09T04:41:27.058+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.059+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:27.060+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:27.079+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-05 00:00:00+00:00
[2025-10-09T04:41:27.086+0000] {standard_task_runner.py:55} INFO - Started process 1323 to run task
[2025-10-09T04:41:27.091+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-05T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpdqpsteq0']
[2025-10-09T04:41:27.095+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask load_customer
[2025-10-09T04:41:27.205+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-05T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.287+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-05T00:00:00+00:00
[2025-10-09T04:41:27.337+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.338+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.355+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251005T000000, start_date=20251009T044127, end_date=20251009T044127
[2025-10-09T04:41:27.384+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.403+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
