[2025-10-09T03:10:31.273+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.287+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T03:10:31.288+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.288+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T03:10:31.289+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T03:10:31.308+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-04 00:00:00+00:00
[2025-10-09T03:10:31.317+0000] {standard_task_runner.py:55} INFO - Started process 3146 to run task
[2025-10-09T03:10:31.322+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-04T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpptu3i4mk']
[2025-10-09T03:10:31.324+0000] {standard_task_runner.py:83} INFO - Job 15: Subtask load_customer
[2025-10-09T03:10:31.438+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [running]> on host c2751665404c
[2025-10-09T03:10:31.528+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-04T00:00:00+00:00
[2025-10-09T03:10:31.531+0000] {logging_mixin.py:137} INFO - Schema file config/schema.json not found.
[2025-10-09T03:10:31.531+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T03:10:31.541+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251004T000000, start_date=20251009T031031, end_date=20251009T031031
[2025-10-09T03:10:31.575+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T03:10:31.592+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:08:08.311+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.325+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:08:08.325+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.326+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:08:08.327+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:08:08.343+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-04 00:00:00+00:00
[2025-10-09T04:08:08.351+0000] {standard_task_runner.py:55} INFO - Started process 4175 to run task
[2025-10-09T04:08:08.354+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpn9234zlr']
[2025-10-09T04:08:08.357+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask load_customer
[2025-10-09T04:08:08.472+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [running]> on host ba400cfa40cd
[2025-10-09T04:08:08.549+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-04T00:00:00+00:00
[2025-10-09T04:08:08.553+0000] {logging_mixin.py:137} INFO - Schema file /opt/airflow/scripts/schemas.json not found.
[2025-10-09T04:08:08.554+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:08:08.565+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251004T000000, start_date=20251009T040808, end_date=20251009T040808
[2025-10-09T04:08:08.608+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:08:08.623+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:16:15.578+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.593+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:16:15.594+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.595+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:16:15.596+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:16:15.611+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-04 00:00:00+00:00
[2025-10-09T04:16:15.616+0000] {standard_task_runner.py:55} INFO - Started process 606 to run task
[2025-10-09T04:16:15.622+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpz6itrlww']
[2025-10-09T04:16:15.625+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask load_customer
[2025-10-09T04:16:15.744+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [running]> on host 947b19fc2afd
[2025-10-09T04:16:15.839+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-04T00:00:00+00:00
[2025-10-09T04:16:15.865+0000] {logging_mixin.py:137} INFO - Error loading data to customers: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5434 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2025-10-09T04:16:15.867+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:16:15.881+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251004T000000, start_date=20251009T041615, end_date=20251009T041615
[2025-10-09T04:16:15.915+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:16:15.937+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-09T04:41:26.940+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:41:26.954+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [queued]>
[2025-10-09T04:41:26.955+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:26.956+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 2
[2025-10-09T04:41:26.957+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2025-10-09T04:41:26.976+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): load_customer> on 2025-10-04 00:00:00+00:00
[2025-10-09T04:41:26.984+0000] {standard_task_runner.py:55} INFO - Started process 1322 to run task
[2025-10-09T04:41:26.988+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'customer_generator', 'load_customer', 'scheduled__2025-10-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/customer_loader_dag.py', '--cfg-path', '/tmp/tmpm_8ullg3']
[2025-10-09T04:41:26.990+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask load_customer
[2025-10-09T04:41:27.098+0000] {task_command.py:389} INFO - Running <TaskInstance: customer_generator.load_customer scheduled__2025-10-04T00:00:00+00:00 [running]> on host 81fbc710bbce
[2025-10-09T04:41:27.183+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=customer_generator
AIRFLOW_CTX_TASK_ID=load_customer
AIRFLOW_CTX_EXECUTION_DATE=2025-10-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2025-10-04T00:00:00+00:00
[2025-10-09T04:41:27.222+0000] {logging_mixin.py:137} INFO - Successfully loaded data to customers
[2025-10-09T04:41:27.223+0000] {python.py:177} INFO - Done. Returned value was: None
[2025-10-09T04:41:27.234+0000] {taskinstance.py:1327} INFO - Marking task as SUCCESS. dag_id=customer_generator, task_id=load_customer, execution_date=20251004T000000, start_date=20251009T044126, end_date=20251009T044127
[2025-10-09T04:41:27.282+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2025-10-09T04:41:27.306+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
